import type { Metadata } from "next";

import { Locale, i18n } from "@/i18n-config";
import { pretendard } from "@/ui/fonts";
import Header from "@/components/header";
import Footer from "@/components/footer";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang} className={pretendard.className}>
      <body className="h-dvh overflow-y-auto flex flex-col max-w-screen-md mx-auto">
        <Header lang={params.lang} />
        <main className="grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
